service: mibr-result-bot

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    DYNAMODB_TABLE: mibr-bot-parameters
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  start:
    handler: handler.start
    name: ${self:service}
    memorySize: 128
    timeout: 10
    events:
      - schedule: rate(3 minutes)

resources: 
  Resources:
    teste3: 
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: parameter
            AttributeType: N
        KeySchema:
          - AttributeName: parameter
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
